import { test, expect } from "@playwright/test";

test.describe("Overview", () => {
  test("shows stat tiles and top narratives from the composition API", async ({ page }) => {
    await page.goto("/overview");
    await expect(page.getByText("Event volume")).toBeVisible();
    await expect(page.getByText("Cross-chain bridge X exploit").first()).toBeVisible();
    await expect(page.getByText("Zero-knowledge proof scaling breakthrough")).toBeVisible();
  });

  test("shows empty states gracefully when the API returns no signal", async ({ page }) => {
    await page.route("**/api/overview", (route) =>
      route.fulfill({
        json: {
          volume: 0,
          sentiment_distribution: {},
          top_narratives: [],
          active_communities: 0,
          anomalies: [],
        },
      })
    );
    await page.goto("/overview");
    await expect(page.getByText("No sentiment signal yet.")).toBeVisible();
    await expect(page.getByText("No anomalies above the trend-score threshold")).toBeVisible();
    await expect(page.getByText("No narratives detected yet.")).toBeVisible();
  });

  test("shows an error state and can retry when the API is unreachable", async ({ page }) => {
    await page.route("**/api/overview", (route) => route.abort("failed"));
    await page.goto("/overview");
    await expect(page.getByText("Couldn't load this view")).toBeVisible();
    await expect(page.getByRole("button", { name: "Retry" })).toBeVisible();
  });
});

test.describe("Timeline", () => {
  test("renders a series per narrative and can filter to one", async ({ page }) => {
    await page.goto("/timeline");
    await expect(page.getByText("Volume over time")).toBeVisible();
    await page.getByRole("combobox").selectOption("topic-002");
    await expect(page.getByText("Sentiment overlay")).toBeVisible();
  });
});

test.describe("Narratives (topic drill-down)", () => {
  test("lists narratives and drills into evidence, sentiment, and communities", async ({ page }) => {
    await page.goto("/topics");
    await page.getByText("Cross-chain bridge X exploit").click();

    await expect(page).toHaveURL(/\/topics\/topic-002/);
    await expect(page.getByRole("heading", { name: "Affected communities" })).toBeVisible();
    await expect(page.getByText(/Confirmed: bridge X exploited/)).toBeVisible();
  });
});

test.describe("Network", () => {
  test("renders graph metrics and the topology view", async ({ page }) => {
    await page.goto("/network");
    await expect(page.getByText("Propagation depth")).toBeVisible();
    await expect(page.getByText("Communities & propagation")).toBeVisible();
    await expect(page.locator("#cy, [style*='height: 420px']").first()).toBeVisible();
  });
});

test.describe("Audience", () => {
  test("shows a low-confidence warning for a low-confidence topic", async ({ page }) => {
    await page.goto("/audience");
    await page.getByRole("combobox").selectOption("topic-002");
    await expect(page.getByText(/Confidence is below 50%/)).toBeVisible();
  });

  test("shows an insufficient-evidence empty state when sample size is zero", async ({ page }) => {
    await page.route("**/api/audience*", (route) =>
      route.fulfill({ json: { categories: {}, unknown_share: 1.0, sample_size: 0, confidence: 0.0 } })
    );
    await page.goto("/audience");
    await expect(page.getByText("Insufficient evidence for an audience estimate")).toBeVisible();
  });
});

test.describe("Investigation", () => {
  test("builds a cross-dimensional explanation and generates a report with an audit trail", async ({ page }) => {
    await page.goto("/investigation");
    await page.getByRole("combobox").selectOption("topic-002");
    await page.getByRole("button", { name: "Build cross-dimensional explanation" }).click();

    await expect(page.getByText("Cross-dimensional finding")).toBeVisible();
    await expect(page.getByText(/confidence/).first()).toBeVisible();

    await page.getByRole("button", { name: "Generate report" }).click();

    await expect(page.getByText("Audit record")).toBeVisible();
    await expect(page.getByText(/Generated by: template/)).toBeVisible();
    await expect(page.getByText(/Evidence event IDs:/)).toBeVisible();
  });
});
